export const LOAD = 'AIRAMARKET_LOAD'
export const MODULE = 'AIRAMARKET_MODULE'
export const SET_ASKS_ORDERS = 'AIRAMARKET_SET_ASKS_ORDERS'
export const SET_BIDS_ORDERS = 'AIRAMARKET_SET_BIDS_ORDERS'
